services:
  mongodb:
    image: mongo:7.0
    container_name: restaurant_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: restaurant_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - restaurant_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: restaurant_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongodb:27017
      DATABASE_NAME: restaurant_db
      API_HOST: 0.0.0.0
      API_PORT: 8000
      LOG_LEVEL: INFO
      ENABLE_METRICS: true
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  restaurant_network:
    driver: bridge
